### PR TITLE
plugins: amazon: add .in

### PR DESCRIPTION
**Pull request by thewisenerd**

### CODE REVIEW

**Comment by tuxxy** [comment]
Looks like the maintainers aren't reviewing pull requests anymore.
I'm actively maintaining my fork of the project at https://github.com/tuxxy/CloudBot.

If you submit your pull request there, I'll merge it.

**Comment by Red-M** [comment]
We don't allow PRs directly into the master branch.
PRs should be made into the py3.4 branch before being pushed into master.
Please read up on how unstable and stable work and why separation for untested code is a good thing towards code quality and production.

**Comment by Red-M** [comment]
In the sake of keeping the conversation in one stream please move it to PR #212

**Comment by daboross** [comment]
Merged into python3.4.

**Pull request closed without merging**
