### PR TITLE
chatbot.py - Using while loops

### PR DESCRIPTION
**Pull request by foxlet**
Using while statements make more sense if we get only one ad or more than two.

### CODE REVIEW

**Comment by daboross** [comment]
Not sure, but I think it might be a good idea to have this in a for loop rather than a while loop, repeating 5-10 times maybe, just because we don't want plugins hanging indefinitely if something goes wrong.

**Comment by foxlet** [comment]
If that's the case, a timeout value can be added and checked against, to prevent a hanging module.

**Comment by lukeroge** [comment]
Or a simple limit on loop iterations

**Comment by lukeroge** [comment]
Ah, you did do that, I was confused by the message.

**Pull request merged**
