### PR TITLE
Bring on the biscuits!

### PR DESCRIPTION
**Pull request by SilverCory**
The biscuit shall prevail.

A biscuit and a cookie, even in other countries, are not the same! Whilst having similar properties, biscuits have more variety, better flavour and are much better for dunking.

Now whilst I am not a dunker, several of us British folk enjoy our biscuits for dunking. We shall bring justice to the biscuit and overcome the cookie! For you should not judge how much a man is British by the amount of tea that they drink, but by the Biscuits that they eat!

### CODE REVIEW

**Comment by TheDoctorsLife** [comment]
No!!!!!!!! THE COOKIES MUST PREVAIL. They are really tasty, & sugary.

**Comment by Red-M** [comment]
[wtf am I reading?](http://cdn.red-m.net/static/what-the-fuck-am-i-reading.jpg)

**Comment by acecheese** [comment]
@TheDoctorsLife I'm not sure what would be more sugary.. The only proper "cookie" I've had is oreos and cookies themselves.. In my experience, the cookies are less sugary.. Bickies and cookies are not the same thing. :"(

@Red-M a British man's defence of the Biscuit.

**Comment by edwardslabs** [comment]
This command will return an error the way it is written. (hint: size is not defined)

**Comment by edwardslabs** [comment]
Please fix and re-submit to the Python3.4 branch instead of  the master branch.

**Pull request closed without merging**
