### PR TITLE
Fixes issue #226

### PR DESCRIPTION
**Pull request by tuxxy**
This uses the nondeprecated psutil functions.

### CODE REVIEW

**Comment by tuxxy** [comment]
@lukeroge Is anyone going to merge this?

For an active project, it seems odd that the last commit has been three months ago when there are plenty of solutions to already preexisting issues here.

**Comment by tuxxy** [comment]
Requesting someone pull this, please.

You're using deprecated functions. Your lack of attention to this problem is irresponsible to this project.

**Comment by edwardslabs** [comment]
@tuxxy why throw a tantrum? What is so critical about your pr? Pull requests should be sent to the python3.4 branch not the master branch.

**Comment by tuxxy** [comment]
No tantrum, it's just irresponsible to maintain a project and not give it any attention when it needs it. You say they should be sent to the python3.4 branch, sure, that's fine. But, you still haven't merged any valid pull requests for **seven months** or given any attention to some of these entirely valid issues.

**Comment by tuxxy** [comment]
I accidentally committed fixes to other issues on this branch when I wasn't paying attention, so I closed the request, FYI.

**Comment by pajenterprisesllc** [comment]
Corporations commodities Committee.

**Pull request closed without merging**
