### PR TITLE
Emacs vim alias

### PR DESCRIPTION
**Pull request by Redrield**
While I was on the Spigot IRC, I noticed that one of the larts in CloudBot's larts.txt was "puts 'alias vim=emacs' in {user}'s /etc/profile"
I use emacs, and this made me sad, so I added the polar opposite of that right next to it "puts 'alias emacs=vim in {user}'s /etc/profile."

### CODE REVIEW

**Comment by pangeacake** [comment]
redrield pls emacs is booty

**Comment by Red-M** [comment]
`export EDITOR=nano`

**Comment by Red-M** [comment]
`export EDITOR=nano`

**Comment by knight-ryu12** [comment]
Don't forget to add visudo to use nano lol

**Comment by daboross** [comment]
`puts 'alias emacs=ed' in {user}'s /etc/profile`

**Pull request closed without merging**
