### PR TITLE
Update correction.py

### PR DESCRIPTION
**Pull request by Red-M**
Corrected security hole.

### CODE REVIEW

**Comment by Red-M** [comment]
@lukeroge 
FYI.

**Comment by lukeroge** [comment]
no idea if this works but cant hurt so yaayy

**Comment by edwardslabs** [comment]
The replacement should be done on lines 31 and 34 for the mod_msg variable.

**Comment by Red-M** [comment]
actually I can do them earlier at line 19 because the replace is never modified.

**Comment by Red-M** [comment]
Also: https://github.com/rmmh/skybot/commit/1281756d4969fba109398be2a4bace110174ca0f

**Comment by edwardslabs** [comment]
Making the change in line 19 does not fix the issue for me.

**Pull request merged**
