### PR TITLE
Fixing soundcloud py regex.

### PR DESCRIPTION
**Pull request by knight-ryu12**
I think commit is messed up. 
Idk why it happening.

### CODE REVIEW

**Comment by knight-ryu12** [comment]
Hmm. I'll make another pr with one commit. CLOSING.

**Comment by daboross** [comment]
I can just merge the last one, it'll be fine.

The thing with the multiple branches is that the `master` branch of this repository is not the current version, but rather an old version for a previous python version. The `python3.4` branch has many updates, and is, as the name suggests, for python3.4.

**Comment by daboross** [comment]
Merged into python3.4. (not via github, but it is merged.)

**Comment by tuxxy** [comment]
Holy shit, someone merged something!!! PRAISE TORVALDS.

**Pull request closed without merging**
