### PR TITLE
Small fix at soundcloud.py regex - for mobile soundcloud support

### PR DESCRIPTION
**Pull request by knight-ryu12**
I added new regex for Soundcloud mobile app support for who using IRC client with mobile

### CODE REVIEW

**Comment by tuxxy** [comment]
It looks like the maintainers have completely left the project alone. They're not merging or reviewing pull requests it looks like. If you submit your pull request on my fork, I'll merge it.
Unlike these guys, I'm actively patching it because my organization likes this bot, but it's a shame the devs have completely left it for dead.

https://github.com/tuxxy/CloudBot/

**Comment by Red-M** [comment]
We don't allow PRs directly into the master branch.
PRs should be made into the py3.4 branch before being pushed into master.
Please read up on how unstable and stable work and why separation for untested code is a good thing towards code quality and production.

**Comment by tuxxy** [comment]
You don’t need to explain to me how stable and unstable branches work.
1) No one has even talked about the issues and the pull requests.
2) You guys have practically ignored the issues and pull requests people have made. You don’t even discuss them, it seems. Again, the last merged pull request was **seven months** ago.

Ignoring the people who work on the project and fix these issues is one way to kill it really quickly.

**Comment by Red-M** [comment]
I'm not able to accept PRs for the project and @lukeroge is busy with other personal projects. Myself and others help out when we can.

Also simply because work isn't showing up on the git repo doesn't mean that we're ignoring people. Some of us have other commitments to fulfill and thus don't have the time do work on this as much as we used to. Blatantly advertising your own fork doesn't look good to some of us who have invested time behind the scenes.

**Comment by tuxxy** [comment]
I’m glad you’re busy with personal projects and have lives outside of a simple project.
However, if you’re too busy to be an active maintainer or dev team member, then you’re too busy to be responsible for the project.

If it doesn’t look good to you people that have invested time in it, maybe you should think twice about how much time you’re going to spend in the future on it if you’re going to consider it your project.

**Comment by Red-M** [comment]
Blatant copy pasting to the PRs with your fork advertised does not look good regardless.
I don't make the choices of who gets push access to the repo, only Luke does.
Also using that statement means that if we don't plan to commit anytime soon we just shouldn't commit at all.

**Comment by tuxxy** [comment]
I don’t care about your feelings on me advertising my maintained fork of your project.

If you’re not willing to put the time into maintaining a popular repo, don’t be a maintainer or a part of the dev team.

**Comment by Red-M** [comment]
Regardless you should have raised this in an issue and not the PRs.
I also never mentioned that I was a maintainer or a lead dev or that this is how I felt about what you did.

**Comment by tuxxy** [comment]
Here’s an argument:
Would any of you even have responded (or cared) if I didn’t post links to my fork?
To be honest, I think that’s the only reason why people are responding. No one has responded to any of the issues or PRs that need attention, so I did myself.

**Comment by Red-M** [comment]
Now you're just wanting to bring argument and ignore what I've said.
Many people who have made commits do care about the project but two wrongs don't make a right.

This is free software that is written in the free time of many of the people who have committed, if you want to keep it up to date that's fine but the way you've approached this is very poor.

**Comment by tuxxy** [comment]
All I'm saying is the maintainers are doing a poor job at maintaining it. If it means I need to fork it and advertise it to light some fires under some asses, so be it.

Again, if you're not willing to put the time into maintaining a popular project, don't be a maintainer or a dev team member.

**Comment by Red-M** [comment]
This is going nowhere and you're clearly not listening.

**Comment by knight-ryu12** [comment]
Well, STOP. really Stop. both of guys.

**Comment by knight-ryu12** [comment]
this PR is closed. okay?

**Comment by knight-ryu12** [comment]
Mention, Well. that's how github works. "work together".

**Comment by tuxxy** [comment]
You closing this pull request doesn't do or help anything.

**Comment by daboross** [comment]
@knight-ryu12 Is the new pull request from you the same commit as this?

**Comment by knight-ryu12** [comment]
Yes. same. But seems it having wrong commit, I'll figure out later

**Comment by daboross** [comment]
Merged.

**Pull request closed without merging**
